// <auto-generated />
using System;
using AuctionService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuctionService.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    partial class AuctionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuctionService.Domain.Entities.Auction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BidCount")
                        .HasColumnType("int");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExtendedUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("MinimumIncrement")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("StartingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Auctions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            BidCount = 2,
                            CategoryId = new Guid("c1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 9, 7, 15, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrice = 45000m,
                            Description = "Laptop profesional Apple M3 Max en estado impecable con caja original y cargador 140W.",
                            EndDate = new DateTime(2026, 9, 7, 16, 25, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80",
                            MinimumIncrement = 2000m,
                            RowVersion = new byte[0],
                            SellerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            StartDate = new DateTime(2026, 9, 7, 15, 0, 0, 0, DateTimeKind.Utc),
                            StartingPrice = 30000m,
                            Status = "Active",
                            Title = "MacBook Pro M3 Max 16 inch 36GB RAM",
                            WinnerId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            BidCount = 1,
                            CategoryId = new Guid("c2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 9, 7, 14, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrice = 120000m,
                            Description = "Edición de colección con certificado de autenticidad y service reciente.",
                            EndDate = new DateTime(2026, 9, 7, 16, 0, 45, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=80",
                            MinimumIncrement = 5000m,
                            RowVersion = new byte[0],
                            SellerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            StartDate = new DateTime(2026, 9, 7, 14, 0, 0, 0, DateTimeKind.Utc),
                            StartingPrice = 100000m,
                            Status = "Active",
                            Title = "Reloj Rolex Submariner Date 1998 Original",
                            WinnerId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            BidCount = 0,
                            CategoryId = new Guid("c2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 9, 7, 16, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrice = 80000m,
                            Description = "Instrumento de gama alta con estuche rigido Custom Shop.",
                            EndDate = new DateTime(2026, 9, 9, 16, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1550985616-10810253b84d?auto=format&fit=crop&w=800&q=80",
                            MinimumIncrement = 2500m,
                            RowVersion = new byte[0],
                            SellerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            StartDate = new DateTime(2026, 9, 8, 16, 0, 0, 0, DateTimeKind.Utc),
                            StartingPrice = 80000m,
                            Status = "Upcoming",
                            Title = "Guitarra Gibson Les Paul Standard 1959 Reissue"
                        },
                        new
                        {
                            Id = new Guid("a4444444-4444-4444-4444-444444444444"),
                            BidCount = 3,
                            CategoryId = new Guid("c3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 9, 5, 16, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrice = 28000m,
                            Description = "Chaqueta clásica de cuero vacuno talle M en excelente estado.",
                            EndDate = new DateTime(2026, 9, 7, 15, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80",
                            MinimumIncrement = 1000m,
                            RowVersion = new byte[0],
                            SellerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            StartDate = new DateTime(2026, 9, 5, 16, 0, 0, 0, DateTimeKind.Utc),
                            StartingPrice = 15000m,
                            Status = "Active",
                            Title = "Chaqueta de Cuero Vintage Schott NYC",
                            WinnerId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("a5555555-5555-5555-5555-555555555555"),
                            BidCount = 0,
                            CategoryId = new Guid("c4444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 9, 4, 16, 0, 0, 0, DateTimeKind.Utc),
                            CurrentPrice = 50000m,
                            Description = "Scooter urbano 45km autonomía con freno de disco y pantalla digital.",
                            EndDate = new DateTime(2026, 9, 7, 14, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://images.unsplash.com/photo-1597086884617-64b58e72efcb?auto=format&fit=crop&w=800&q=80",
                            MinimumIncrement = 2000m,
                            RowVersion = new byte[0],
                            SellerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            StartDate = new DateTime(2026, 9, 4, 16, 0, 0, 0, DateTimeKind.Utc),
                            StartingPrice = 50000m,
                            Status = "Active",
                            Title = "Scooter Eléctrico Xiaomi Pro 2"
                        });
                });

            modelBuilder.Entity("AuctionService.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("AuctionService.Domain.Entities.Bid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BidTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsWinningBid")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.ToTable("Bids");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-111111111111"),
                            Amount = 35000m,
                            AuctionId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            BidTime = new DateTime(2026, 9, 7, 15, 15, 0, 0, DateTimeKind.Utc),
                            IsWinningBid = false,
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222222"),
                            Amount = 45000m,
                            AuctionId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            BidTime = new DateTime(2026, 9, 7, 15, 30, 0, 0, DateTimeKind.Utc),
                            IsWinningBid = true,
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("b3333333-3333-3333-3333-333333333333"),
                            Amount = 120000m,
                            AuctionId = new Guid("a2222222-2222-2222-2222-222222222222"),
                            BidTime = new DateTime(2026, 9, 7, 15, 50, 0, 0, DateTimeKind.Utc),
                            IsWinningBid = true,
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("b4444444-4444-4444-4444-444444444444"),
                            Amount = 28000m,
                            AuctionId = new Guid("a4444444-4444-4444-4444-444444444444"),
                            BidTime = new DateTime(2026, 9, 7, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsWinningBid = true,
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("AuctionService.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1111111-1111-1111-1111-111111111111"),
                            Description = "Laptops, Smartphones, Consolas y Gadgets",
                            Icon = "Computer",
                            Name = "Tecnología"
                        },
                        new
                        {
                            Id = new Guid("c2222222-2222-2222-2222-222222222222"),
                            Description = "Arte, Antigüedades, Relojes y Rarezas",
                            Icon = "Diamond",
                            Name = "Coleccionables"
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-3333-3333-333333333333"),
                            Description = "Ropa Vintage, Zapatillas y Accesorios de Lujo",
                            Icon = "Checkroom",
                            Name = "Indumentaria"
                        },
                        new
                        {
                            Id = new Guid("c4444444-4444-4444-4444-444444444444"),
                            Description = "Autos, Motos, Scooters y Movilidad",
                            Icon = "DirectionsCar",
                            Name = "Vehículos"
                        });
                });

            modelBuilder.Entity("AuctionService.Domain.Entities.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("FinalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("AuctionService.Domain.Entities.Auction", b =>
                {
                    b.HasOne("AuctionService.Domain.Entities.Category", "Category")
                        .WithMany("Auctions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AuctionService.Domain.Entities.Bid", b =>
                {
                    b.HasOne("AuctionService.Domain.Entities.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("AuctionService.Domain.Entities.Auction", b =>
                {
                    b.Navigation("Bids");
                });

            modelBuilder.Entity("AuctionService.Domain.Entities.Category", b =>
                {
                    b.Navigation("Auctions");
                });
#pragma warning restore 612, 618
        }
    }
}
